name = "huddless"
main = "src/index.ts"
usage_model = "bundled"
compatibility_date = "2022-09-16"
node_compat = true

[durable_objects]
bindings = [
  { name = "HUDDLESS", class_name = "Huddless" }
]

[[migrations]]
tag = "v1"
new_classes = ["Huddless"]

[vars]
HUDDLESS_NAME = "huddless_chat"